"""
Pacific CLI — Main entry point.

SECURITY:
  - This binary contains ZERO secrets — no API keys, no tokens, nothing.
  - Authentication = Windows Store license token (generated by the OS).
  - No login. No registration. No accounts. No database.
  - User buys/trials from Microsoft Store → opens terminal → types command → works.

Usage:
  pacific "What's the outlook for tech?"     Quick query (default)
  pacific chat [message]                     Interactive chat or single query
  pacific analyze [query]                    Financial analysis
  pacific sentiment [headline]               Sentiment classification
  pacific portfolio [--holdings ...] [...]   Portfolio optimization
  pacific plans                              Show pricing
  pacific config [--proxy-url ...] [...]     Configure preferences
  pacific health                             Check server status

Examples:
  pacific "Analyze AAPL earnings beat"
  pacific chat --think
  pacific analyze "NVDA technical outlook" --ticker NVDA --timeframe 1W
  pacific sentiment "Fed announces surprise rate cut of 50bps"
"""

import argparse
import sys

from . import __version__
from .commands import (
    cmd_chat, cmd_analyze, cmd_sentiment, cmd_portfolio,
    cmd_plans, cmd_config, cmd_health,
)


def main():
    parser = argparse.ArgumentParser(
        prog="pacific",
        description="🌊 Pacific — Elite Quantitative Financial AI",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Quick start (no login needed — Microsoft Store handles auth):\n"
            "  pacific \"What's happening with TSLA?\"\n"
            "  pacific chat                      Interactive mode\n"
            "  pacific chat --think               With reasoning\n"
            "\n"
            "Analysis:\n"
            "  pacific analyze --ticker AAPL --timeframe 1W \"earnings impact\"\n"
            "  pacific sentiment \"Inflation data comes in hotter than expected\"\n"
            "  pacific portfolio --holdings \"SPY 60%, AGG 40%\" --risk low\n"
            "\n"
            "Get Pacific: Microsoft Store → search 'Pacific Financial AI'\n"
            "Docs:        https://pacific.grrn.io/docs\n"
        ),
    )
    parser.add_argument("-v", "--version", action="version", version=f"pacific-cli {__version__}")

    subparsers = parser.add_subparsers(dest="command", help="Available commands")

    # ── chat (also the default if no subcommand) ──
    chat_parser = subparsers.add_parser("chat", help="Interactive chat or single query")
    chat_parser.add_argument("message", nargs="*", help="Query (omit for interactive mode)")
    chat_parser.add_argument("--think", action="store_true", help="Enable thinking/chain-of-thought")
    chat_parser.set_defaults(func=cmd_chat)

    # ── analyze ──
    analyze_parser = subparsers.add_parser("analyze", help="Financial analysis query")
    analyze_parser.add_argument("query", nargs="*", help="Analysis query")
    analyze_parser.add_argument("--ticker", "-t", help="Stock ticker symbol")
    analyze_parser.add_argument("--timeframe", "-tf", help="Timeframe (1D, 1W, 1M, etc.)")
    analyze_parser.add_argument("--think", action="store_true", help="Enable thinking mode")
    analyze_parser.set_defaults(func=cmd_analyze)

    # ── sentiment ──
    sentiment_parser = subparsers.add_parser("sentiment", help="Classify financial sentiment")
    sentiment_parser.add_argument("text", nargs="*", help="Text to classify")
    sentiment_parser.set_defaults(func=cmd_sentiment)

    # ── portfolio ──
    portfolio_parser = subparsers.add_parser("portfolio", help="Portfolio optimization")
    portfolio_parser.add_argument("--action", "-a", default="analyze",
                                  choices=["analyze", "optimize", "rebalance", "risk"],
                                  help="Portfolio action")
    portfolio_parser.add_argument("--holdings", "-H", help="Current holdings")
    portfolio_parser.add_argument("--risk", "-r", choices=["low", "moderate", "high", "aggressive"],
                                  help="Risk tolerance")
    portfolio_parser.add_argument("--goal", "-g", help="Investment goal")
    portfolio_parser.set_defaults(func=cmd_portfolio)

    # ── plans ──
    plans_parser = subparsers.add_parser("plans", help="Show pricing info")
    plans_parser.set_defaults(func=cmd_plans)

    # ── config (ZERO secrets) ──
    config_parser = subparsers.add_parser("config", help="Configure CLI preferences")
    config_parser.add_argument("--proxy-url", help="Set proxy gateway URL")
    config_parser.add_argument("--max-tokens", type=int, help="Default max tokens")
    config_parser.add_argument("--temperature", type=float, help="Default temperature")
    config_parser.add_argument("--thinking", help="Enable thinking (true/false)")
    config_parser.set_defaults(func=cmd_config)

    # ── health ──
    health_parser = subparsers.add_parser("health", help="Check server status")
    health_parser.set_defaults(func=cmd_health)

    args = parser.parse_args()

    if not args.command:
        # No subcommand — treat remaining args as a quick chat query
        remaining = sys.argv[1:]
        if remaining and not remaining[0].startswith("-"):
            # pacific "What's happening with TSLA?" → quick single query
            class QuickArgs:
                message = remaining
                think = False
            cmd_chat(QuickArgs())
        else:
            parser.print_help()
        return

    args.func(args)


if __name__ == "__main__":
    main()
